CREATE DATABASE UPD8_CORE;
GO

USE UPD8_CORE
GO

CREATE TABLE [dbo].[CUSTOMER]  
(     
    [ID_CUSTOMER] BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1), 
    [DOCUMENT] VARCHAR(15) NOT NULL, 
    [NAME] VARCHAR(150) NOT NULL, 
    [BIRTH] DATE NOT NULL, 		
    [GENDER] VARCHAR(5) NOT NULL,
    [ADDRESS] VARCHAR(250) NOT NULL, 
    [STATE] VARCHAR(50) NOT NULL, 
    [CITY] VARCHAR(100) NOT NULL,
);
GO

INSERT INTO CUSTOMER([DOCUMENT], [NAME], [BIRTH], [GENDER], [ADDRESS], [STATE], [CITY])
VALUES('111.222.333-44', 'Usuário teste 1', '2000-04-10', 'M', 'Rua teste, casa 123', 'SC', 'Floripa');